Move Raid tools, Uncrypt, etc...

diff --git a/initramfs/init b/initramfs/init
--- a/initramfs/init
+++ b/initramfs/init
@@ -36,19 +36,84 @@ fatal() {
 
 
 z_fsck() {
-	[ -n "$1" ] || fatal "z_fsck(): Wrong argument error. Value format - DEV,FS. Example: z_fsck=\"vg0/system:ext4,vg0/data:ext4\" (no /dev prefix)"
+	[ -n "$1" ] || fatal "z_fsck(): Wrong argument error. Example: z_fsck=\"vg0/system:ext4,vg0/data:ext4\" (no /dev prefix)"
 
 	local FRIENDLY_ARGS=
 	local DEV=
 	local FS=
 
-	FRIENDLY_ARGS=`echo "$1" | sed -r 's/,/ /g'`
+	FRIENDLY_ARGS=$(echo "$1" | sed -r 's/,/ /g')
 
 	for CHECK in ${FRIENDLY_ARGS}; do
 		DEV=`echo "${CHECK}" | awk -F: '{print $1}'`
 		FS=`echo "${CHECK}" | awk -F: '{print $2}'`
 		info "Force check file system ${FS} on /dev/${DEV}"
 		/sbin/fsck -f -p -t "${FS}" -f "/dev/${DEV}" || warn "z_fsck(): Cannot check filesystem on /dev/${DEV} (${FS})."
+	done
+}
+
+
+z_ip() {
+	[ -n "$1" ] || fatal "z_ip(): Wrong argument error. Example: z_ip=\"eth0:192.168.0.100/24[:192.168.0.1][,eth1:10.0.0.42/8[:10.0.0.254]]\")"
+	FRIENDLY_ARGS=`echo "$1" | sed -r 's/,/ /g'`
+	for NETCFG in ${FRIENDLY_ARGS}; do
+		local DEV=
+		local IP_WITH_MASK=
+		local GW=
+
+		DEV=$(echo "${NETCFG}" | cut -d: -f1)
+		IP_WITH_MASK=$(echo "${NETCFG}" | cut -d: -f2)
+		GW=$(echo "${NETCFG}" | cut -d: -f3)
+
+		local IP=
+		local PREFIX=
+		local MASK=
+
+		IP=$(echo "${IP_WITH_MASK}" | cut -d/ -f1)
+		PREFIX=$(echo "${IP_WITH_MASK}" | cut -d/ -f2)
+		case "$PREFIX" in
+			8)
+				MASK=255.0.0.0
+				;;
+			16)
+				MASK=255.255.0.0
+				;;
+			24)
+				MASK=255.255.255.0
+				;;
+			*)
+				fatal "z_ip(): Unsupported IP prefix '$PREFIX'"
+				;;
+		esac
+
+		info "Set up IP address: $IP $MASK for dev $DEV"
+		ifconfig "$DEV" "$IP" netmask "$MASK"
+		echo "ifconfig $DEV 0.0.0.0" >> /tmp/cleanup.sh
+		echo "ifconfig $DEV down" >> /tmp/cleanup.sh
+
+		if [ -z "$GW" ]; then
+			info "Gateway is not defined"
+		else
+			info "Set up defult route: $GW"
+			route add default gw "$GW" "$DEV"
+		fi
+	fi
+}
+
+
+
+z_md() {
+	[ -n "$1" ] || fatal "z_md():  Wrong argument error. Example: z_md=\"md0:sda1:[sdb1:...][,md1:sda5:[sdb5:...]]\""
+	FRIENDLY_ARGS=$(echo "$1" | sed -r 's/,/ /g')
+	for MDTARGET in ${FRIENDLY_ARGS}; do
+		local MD_DEV=
+		local MEMBER_DEVS=
+
+		MD_DEV=/dev/$(echo "${MDTARGET}" | cut -d: -f1)
+		MEMBER_DEVS=$(echo "${SNAP}" | cut -d: -f2- | cut -d: -f2- | sed -r 's/:/ /g' | sed 's/[^ ]* */\/dev\/&/g')
+
+		/sbin/mdadm --assemble --run ${MD_DEV} ${MEMBER_DEVS} || fatal "z_md(): Cannot MD assemble: ${MD_DEV} ${MEMBER_DEVS}"
+		#/sbin/mdadm --assemble --update=name --run ${MD_DEV} ${MEMBER_DEVS} || fatal "z_md(): Cannot MD assemble: ${MD_DEV} ${MEMBER_DEVS}"
 	done
 }
 
@@ -105,35 +170,12 @@ z_shell() {
 	echo
 }
 
-z_uncrypt() {
-	[ -n "$1" ] || fatal "z_uncrypt(): Wrong argument error. Example: z_uncrypt=\"sda2,uncrypted-sda2[,allow-discards]\" (no /dev prefix)"
-	/uncrypt.sh "$1" || fatal "z_uncrypt(): Script /uncrypt.sh failed."
-	return 0
-}
-
-z_vgs() {
-	[ -n "$1" ] || fatal "z_vgs(): Wrong argument error. Example: z_vgs=\"vg0,vg1,vg2,...\" (no /dev prefix)"
-
-	info " Scanning for Volume Groups"
-	/sbin/vgscan || fatal "z_vgs(): Cannot scan volume groups"
-
- 	local FRIENDLY_ARGS=
-
-	FRIENDLY_ARGS=`echo "$1" | sed -r 's/,/ /g'`
-
-	for VG in ${FRIENDLY_ARGS}; do
- 		info " Activating Volume Group: $VG"
-		/sbin/vgchange --activate y "$VG" || fatal "z_vgs(): Cannot activate volume $VG"
-	done
-
-	# /sbin/vgscan --mknodes || fatal "z_vgs(): Cannot make volume group nodes"
-}
 z_snap() {
 	[ -n "$1" ] || fatal "z_snap(): Wrong argument error. Example: z_snap=\"vg0/luks-root:10G,vg0/luks-data:250M\""
 
  	local FRIENDLY_ARGS=
 
-	FRIENDLY_ARGS=`echo "$1" | sed -r 's/,/ /g'`
+	FRIENDLY_ARGS=$(echo "$1" | sed -r 's/,/ /g')
 
 	for SNAP in ${FRIENDLY_ARGS}; do
 		local LV_DEV=
@@ -143,7 +185,6 @@ z_snap() {
 
 		LV_DEV=/dev/$(echo "${SNAP}" | awk -F: '{print $1}')
 		LV_SIZE=$(echo "${SNAP}" | awk -F: '{print $2}')
-		#LV_SNAPNAME=`basename "${LV_DEV}"`-bootsnap`date '+%Y%m%d%H%M%S'`
 		LV_SNAPNAME=$(basename "${LV_DEV}")-bootsnap
 		LV_SNAPDEV=$(dirname "${LV_DEV}")/${LV_SNAPNAME}
 
@@ -160,14 +201,41 @@ z_snap() {
 	done
 }
 
+z_ssh() {
+	[ ! -f /root/dropbear.rsa ] && /usr/bin/dropbearkey -t rsa -f /root/dropbear.rsa
+	[ ! -f /root/dropbear.dss ] && /usr/bin/dropbearkey -t dss -f /root/dropbear.dss
+
+	/usr/sbin/dropbear -r /root/dropbear.rsa -d /root/dropbear.dss
+	echo "pkill -f /usr/sbin/dropbear" >> /tmp/cleanup.sh
+}
+
+z_uncrypt() {
+	[ -n "$1" ] || fatal "z_uncrypt(): Wrong argument error. Example: z_uncrypt=\"sda2:uncrypted-sda2[:allow-discards][,vg0/luks-root:uncrypted-root[:allow-discards]]\" (no /dev prefix)"
+	/uncrypt.sh "$1" || fatal "z_uncrypt(): Script /uncrypt.sh failed."
+	return 0
+}
+
+z_vgs() {
+	[ -n "$1" ] || fatal "z_vgs(): Wrong argument error. Example: z_vgs=\"vg0,vg1,vg2,...\" (no /dev prefix)"
+
+	info " Scanning for Volume Groups"
+	/sbin/vgscan || fatal "z_vgs(): Cannot scan volume groups"
+
+ 	local FRIENDLY_ARGS=
+
+	FRIENDLY_ARGS=$(echo "$1" | sed -r 's/,/ /g')
+
+	for VG in ${FRIENDLY_ARGS}; do
+ 		info " Activating Volume Group: $VG"
+		/sbin/vgchange --activate y "$VG" || fatal "z_vgs(): Cannot activate volume $VG"
+	done
+}
+
+
 # Set up busybox'es symlinks
 /bin/busybox --install -s
 
 ln -s /proc/mounts /etc/mtab || fatal "Cannot link /etc/mtab -> /proc/mounts"
-
-#echo /sbin/mdev > /proc/sys/kernel/hotplug
-#/bin/busybox mdev -s || /bin/sh
-#echo "" > /proc/sys/kernel/hotplug
 
 echo "Starting udev daemon..."
 /sbin/udevd --daemon --resolve-names=never
@@ -176,6 +244,14 @@ udevadm trigger
 udevadm settle
 [ $UDEV_RC -eq 0 ] || fatal "Failed to start udev daemon. Exit code: $UDEV_RC"
 unset UDEV_RC
+
+# Prepare cleanup script
+echo "#!/bin/busybox sh" > /tmp/cleanup.sh
+echo >> /tmp/cleanup.sh
+echo "set -e" >> /tmp/cleanup.sh
+echo >> /tmp/cleanup.sh
+chmod +x /tmp/cleanup.sh
+
 
 # Kernel command-line
 KCMD=$(cat "/proc/cmdline")
@@ -197,9 +273,14 @@ echo "Stopping udev daemon..."
 killall udevd
 sleep 1
 
+if [ -x /tmp/cleanup.sh ]; then
+	echo "Executing cleanup script..."
+	/tmp/cleanup.sh || fatal "Cleanup failed."
+fi
+
 # z_snap=vg0/system-x64_86-gentoo,1G z_root=vg0/system-x64_86-gentoo
 # net.ifnames=1
-# z_ip="eth0,94.154.211.54,255.255.255.0,94.154.211.1" 
+# z_ip="eth0,94.154.211.54,255.255.255.0,94.154.211.1"
 # z_dropbear 
 # z_md="md0,sdb1,sdc1,sdd1,sde1"
 # z_md="md1,sdb2,sdc2"
