Add KERNEL_SLUG to correct handle kernel version like X.Y.Z-r123

diff --git a/initramfs/init b/initramfs/init
--- a/initramfs/init
+++ b/initramfs/init
@@ -326,20 +326,20 @@ if [ -d /newroot/lib ]; then
 	KERNEL_RELEASE=$(uname -r)
 	if [ -d "/lib/modules/${KERNEL_RELEASE}" ]; then
 			echo "Checking modules..."
-			NEED_TO_COPY="no"
+			MODULES_NEED_TO_COPY="no"
 			if [ ! -d "/newroot/lib/modules/${KERNEL_RELEASE}" ]; then
-				NEED_TO_COPY="yes"
+				MODULES_NEED_TO_COPY="yes"
 			else
 				cd /lib/modules/
 				RELEASE_MODULES_SUM=$(find "${KERNEL_RELEASE}" -type f | sort | xargs sha1sum | sha1sum | cut -d' ' -f1)
 				cd /newroot/lib/modules/
 				EXISTING_MODULES_SUM=$(find "${KERNEL_RELEASE}" -type f | sort | xargs sha1sum | sha1sum | cut -d' ' -f1)
 				if [ "${RELEASE_MODULES_SUM}" != "${EXISTING_MODULES_SUM}" ]; then
-					NEED_TO_COPY="yes"
+					MODULES_NEED_TO_COPY="yes"
 				fi
 			fi
 
-			if [ "${NEED_TO_COPY}" = "yes" ]; then
+			if [ "${MODULES_NEED_TO_COPY}" = "yes" ]; then
 				NEWROOT_MOUNT_OPTS=$(grep /newroot /proc/mounts | cut -d' ' -f4)
 				if [ $? -ne 0 ]; then
 					fatal "Cannot obtain mount options of /newroot"
@@ -349,7 +349,7 @@ if [ -d /newroot/lib ]; then
 				if [ ! -d /newroot/lib/modules ]; then
 					mkdir /newroot/lib/modules || fatal "Cannot create /newroot/lib/modules directory"
 				fi
-				cp -a "/lib/modules/${KERNEL_RELEASE}" /newroot/lib/modules/
+				cp -a "/lib/modules/${KERNEL_RELEASE}" /newroot/lib/modules/ || fatal "Failure copy modules"
 				info "Modules ${KERNEL_RELEASE} were copied into /newroot/lib/modules"
 
 				info "Re-mounting the /newroot filesystem with original options '${NEWROOT_MOUNT_OPTS}' ..."
