z_stratum_root: Mount overlay based on MANIFEST data

diff --git a/initramfs/init b/initramfs/init
--- a/initramfs/init
+++ b/initramfs/init
@@ -284,24 +284,77 @@ z_stratum_root() {
 	mount -t "${STRATUM_IMAGES_FS}" -o ro "${STRATUM_IMAGES_DEV}" /run/stratum/images || fatal "Failure mount \"${STRATUM_IMAGES_DEV}\" to /run/stratum/images"
 	mount -t "${STRATUM_STATE_FS}" -o rw "${STRATUM_STATE_DEV}" /run/stratum/state || fatal "Failure mount \"${STRATUM_STATE_DEV}\" to /run/stratum/state"
 
+	local STATE_DIR="/run/stratum/state/${STRATUM_ROOT_IMAGE}"
+
+	if [ ! -d "${STATE_DIR}" ]; then
+		mkdir "${STATE_DIR}" || fatal "z_stratum_root(): Failure create state dir ${STATE_DIR}"
+	fi
+
+	local LAYER_NUMBER=0
+	local IMAGE_HASH="${STRATUM_ROOT_IMAGE}"
+	local LOWERDIRS=
+
+	while [ -n "${IMAGE_HASH}" ]; do
+		local IMAGE_DIR="/run/stratum/images/${IMAGE_HASH}"
+		[ ! -d "${IMAGE_DIR}" ] || fatal "z_stratum_root(): Image ${IMAGE_HASH} does not exist"
+
+		local IMAGE_MANIFEST_FILE="${IMAGE_DIR}/MANIFEST"
+		local IMAGE_DATA_FILE="${IMAGE_DIR}/DATA"
+
+		local LAYER_NAME="layer${LAYER_NUMBER}"
+		local LAYER_DIR="${STATE_DIR}/${LAYER_NAME}"
+
+		if [ ! -d "${LAYER_DIR}" ]; then
+			mkdir "${LAYER_DIR}" || fatal "z_stratum_root(): Failure create layer dir ${STATE_DIR}"
+		fi
+
+		mount -t squashfs -o ro,loop "${IMAGE_DATA_FILE}" "${LAYER_DIR}" || fatal "z_stratum_root(): Failure mount layer \"${IMAGE_DATA_FILE}\" to \"${LAYER_DIR}\""
+
+		if [ -n "${LOWERDIRS}" ]; then
+			LOWERDIRS="${LOWERDIRS}:${LAYER_DIR}"
+		else
+			LOWERDIRS="${LAYER_DIR}"
+		fi
+
+		local BASE_IMAGE_HASH=$(cat "${IMAGE_MANIFEST_FILE}" | grep -e "^BASE: " | rev | cut -d' ' -f1 | rev)
+
+		IMAGE_HASH="${BASE_IMAGE_HASH}"
+		let "LAYER_NUMBER=$LAYER_NUMBER+1"
+	done
+
+	local WORK_DIR="${STATE_DIR}/.work"
+
+	if [ ! -d "${WORK_DIR}" ]; then
+		mkdir "${WORK_DIR}" || fatal "z_stratum_root(): Failure create layer dir ${WORK_DIR}"
+	fi
+
+	local TOP_DIR="${STATE_DIR}/top"
+
+	if [ ! -d "${TOP_DIR}" ]; then
+		mkdir "${TOP_DIR}" || fatal "z_stratum_root(): Failure create layer dir ${TOP_DIR}"
+	fi
+
+	mount -t overlay -o "lowerdir=${LOWERDIRS},workdir=${WORK_DIR},upperdir=${TOP_DIR}" none /newroot || fatal "z_stratum_root(): Failure mount overlay /newroot based on ${LOWERDIRS}"
+
+
 	# echo
 	# info " z_stratum_root() is not implemented yet."
 	# /bin/busybox sh
 
-	set -ex
-	if [ ! -d /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf ]; then
-		mkdir /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf
-	fi
-	if [ ! -d /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/top ]; then
-		mkdir /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/top
-	fi
-	if [ ! -d /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/.work ]; then
-		mkdir /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/.work
-	fi
-	mount -t squashfs -o ro,loop /run/stratum/images/4a76868dae9c5725645532ff44be1b1217f3b7d6e55ec768ea1e46d17f01a968/DATA /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/layer0
-	mount -t squashfs -o ro,loop /run/stratum/images/940c6578ffa80250d7ee8a0a4f25c7c66a7b522d2af9b9c8f19df5ee316e47c8/DATA /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/layer1
-	mount -t squashfs -o ro,loop /run/stratum/images/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/DATA /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/layer2
-	mount -t overlay -o lowerdir=/run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/layer2:/run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/layer1:/run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/layer0,workdir=/run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/.work,upperdir=/run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/top none /newroot
+	# set -ex
+	# if [ ! -d /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf ]; then
+	# 	mkdir /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf
+	# fi
+	# if [ ! -d /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/top ]; then
+	# 	mkdir /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/top
+	# fi
+	# if [ ! -d /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/.work ]; then
+	# 	mkdir /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/.work
+	# fi
+	# mount -t squashfs -o ro,loop /run/stratum/images/4a76868dae9c5725645532ff44be1b1217f3b7d6e55ec768ea1e46d17f01a968/DATA /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/layer0
+	# mount -t squashfs -o ro,loop /run/stratum/images/940c6578ffa80250d7ee8a0a4f25c7c66a7b522d2af9b9c8f19df5ee316e47c8/DATA /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/layer1
+	# mount -t squashfs -o ro,loop /run/stratum/images/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/DATA /run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/layer2
+	# mount -t overlay -o lowerdir=/run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/layer2:/run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/layer1:/run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/layer0,workdir=/run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/.work,upperdir=/run/stratum/state/d6779c7557a8f32fc5f4d636f74925241d9cc37a18d2f27683c3e87e983611bf/top none /newroot
 }
 
 z_uncrypt() {
