Build targets on CI

diff --git a/initramfs/init b/initramfs/init
--- a/initramfs/init
+++ b/initramfs/init
@@ -238,16 +238,16 @@ z_snap() {
 
 		if [ -b "${LV_SNAPDEV}" ]; then
 			if [ "${FORCE}" == "force" ]; then
-				info "	Removing previous snapshot"
+				info "z_snap(): Removing previous snapshot"
 				local LV_ORIGIN=
 				LV_ORIGIN=$(/sbin/lvs "${LV_SNAPDEV}" | tail -n 1 | awk '{print $5}')
-				[ -z "${LV_ORIGIN}" ] && fatal "Looks like ${LV_SNAPDEV} is not a snapshot(has not Pool Origin)! Something wrong in ZXInit configuration! Please check!"
-				/sbin/lvremove -f "${LV_SNAPDEV}" || fatal "Failure remove LV snapshot ${LV_SNAPDEV}"
+				[ -z "${LV_ORIGIN}" ] && fatal "z_snap(): Looks like ${LV_SNAPDEV} is not a snapshot(has not Pool Origin)! Something wrong in ZXInit configuration! Please check!"
+				/sbin/lvremove -f "${LV_SNAPDEV}" || fatal "z_snap(): Failure remove LV snapshot ${LV_SNAPDEV}"
 			else
-				warn "	Skip creation of boot snaphot due it already exist." 
+				warn "z_snap(): Skip creation of boot snaphot due it already exist." 
 			fi
 		else
-			info "	Create LVM snapshot ${LV_SNAPNAME} (size: ${LV_SIZE}) for volume ${LV_DEV}"
+			info "z_snap(): Create LVM snapshot ${LV_SNAPNAME} (size: ${LV_SIZE}) for volume ${LV_DEV}"
 			/sbin/lvcreate --snapshot --permission r --size "${LV_SIZE}" --name "${LV_SNAPNAME}" "${LV_DEV}" || fatal "Failure create LV snapshot."
 		fi
 	done
@@ -259,6 +259,115 @@ z_ssh() {
 
 	/usr/sbin/dropbear -r /root/dropbear.rsa -d /root/dropbear.dss || fatal "Failure start Dropbear SSH Server"
 	echo "pkill -f /usr/sbin/dropbear" >> /tmp/cleanup.sh
+}
+
+__stratum__resolve_image_hash() {
+	local TARGET_IMAGE_ID="$1"
+
+	if (echo $TARGET_IMAGE_ID | grep -Eq "^[0-9a-f]{64}$"); then
+		echo "${TARGET_IMAGE_ID}"
+		return 0
+	fi
+
+	local IMAGE_MANIFEST_FILE="/run/stratum/images/${TARGET_IMAGE_ID}/MANIFEST"
+	if [ -f "${IMAGE_MANIFEST_FILE}" ]; then
+		local TAGET_IMAGE_HASH=
+		TAGET_IMAGE_HASH=$(cat "${IMAGE_MANIFEST_FILE}" | grep -e "^SHA256: " | head -n 1 | rev | cut -d' ' -f1 | rev)
+		if [ $? -ne 0 ]; then
+			return 1
+		fi
+		echo -n "${TAGET_IMAGE_HASH}"
+		return 0
+	fi
+
+	local IMAGE_MANIFEST_URL="http://dl.zxteam.net/stratum/images/${TARGET_IMAGE_ID}/MANIFEST"
+	local REMOTE_MANIFEST_DATA=
+	REMOTE_MANIFEST_DATA=$(curl --fail --silent "${IMAGE_MANIFEST_URL}")
+	if [ $? -ne 0 ]; then
+		return 2
+	fi
+
+	local TAGET_IMAGE_HASH=
+	TAGET_IMAGE_HASH=$(echo "${REMOTE_MANIFEST_DATA}" | grep -e "^SHA256: " | head -n 1 | rev | cut -d' ' -f1 | rev)
+	if [ $? -ne 0 ]; then
+		return 3
+	fi
+	echo -n "${TAGET_IMAGE_HASH}"
+}
+
+__stratum__download_image() {
+	local IMAGE_TAG="$1"
+	if [ -z "${IMAGE_TAG}" ]; then
+		return 127
+	fi
+
+	if ! (echo $IMAGE_TAG | grep -Eq "^[0-9a-f]{64}$"); then
+		return 126
+	fi
+
+	local LOCAL_IMAGE_DIR="/run/stratum/images/${IMAGE_TAG}"
+	if [ ! -d "${LOCAL_IMAGE_DIR}" ]; then
+
+		local LOCAL_IMAGE_DIR_TEMP="/run/stratum/images/${IMAGE_TAG}.tmp"
+		if [ -d "${LOCAL_IMAGE_DIR_TEMP}" ]; then
+			# fatal "Cannot download image due temporary '${LOCAL_IMAGE_DIR_TEMP}' directory already exist."
+			rm -rf "${LOCAL_IMAGE_DIR_TEMP}"
+		fi
+
+		local IMAGE_MANIFEST_URL="http://dl.zxteam.net/stratum/images/${IMAGE_TAG}/MANIFEST"
+		local IMAGE_DATA_URL="http://dl.zxteam.net/stratum/images/${IMAGE_TAG}/DATA"
+
+		mkdir -p "${LOCAL_IMAGE_DIR_TEMP}"
+		if [ $? -ne 0 ]; then
+			# fatal "Failure to create directory ${LOCAL_IMAGE_DIR_TEMP}"
+			return 2
+		fi
+		info "Downloading MANIFEST of ${IMAGE_TAG} ..."
+		curl "${IMAGE_MANIFEST_URL}" --fail --output "${LOCAL_IMAGE_DIR_TEMP}/MANIFEST"
+		if [ $? -ne 0 ]; then
+			rm -rf "${LOCAL_IMAGE_DIR_TEMP}"
+			# fatal "Failure download MANIFEST of image ${IMAGE_TAG}"
+			return 3
+		fi
+		echo
+		info "Downloading DATA of ${IMAGE_TAG} ..."
+		curl "${IMAGE_DATA_URL}" --fail --output "${LOCAL_IMAGE_DIR_TEMP}/DATA"
+		if [ $? -ne 0 ]; then
+			rm -rf "${LOCAL_IMAGE_DIR_TEMP}"
+			# fatal "Failure download DATA of image ${IMAGE_TAG}"
+			return 4
+		fi
+		echo
+
+		mv "${LOCAL_IMAGE_DIR_TEMP}" "${LOCAL_IMAGE_DIR}"
+		if [ $? -ne 0 ]; then
+			rm -rf "${LOCAL_IMAGE_DIR_TEMP}"
+			# fatal "Failure to rename ${LOCAL_IMAGE_DIR_TEMP} to ${LOCAL_IMAGE_DIR}"
+			return 5
+		fi
+
+		info "Image ${IMAGE_TAG} was downloaded successfully."
+	else
+		echo "Image ${IMAGE_TAG} already exist. Skip download."
+	fi
+}
+
+z_stratum_wipe() {
+	[ -n "$1" ] || fatal "z_stratum_root(): Wrong argument error. Example: z_stratum_root=\"vg0/stratum-images,ext4,vg0/stratum-state,ext4\""
+
+	local STRATUM_IMAGES_DEV=
+	local STRATUM_IMAGES_FS=
+	local STRATUM_STATE_DEV=
+	local STRATUM_STATE_FS=
+	local STRATUM_ROOT_IMAGE=
+
+	STRATUM_IMAGES_DEV=/dev/$(echo "$1" | cut -d, -f1)
+	STRATUM_IMAGES_FS=$(echo "$1" | cut -d, -f2)
+	STRATUM_STATE_DEV=/dev/$(echo "$1" | cut -d, -f3)
+	STRATUM_STATE_FS=$(echo "$1" | cut -d, -f4)
+
+	mkfs.${STRATUM_IMAGES_FS} -L stratum-images -F -N 256 "${STRATUM_IMAGES_DEV}" || fatal "z_stratum_root(): Failure mkfs on \"${STRATUM_IMAGES_DEV}\""
+	mkfs.${STRATUM_STATE_FS} -L stratum-state -F -N 524288 "${STRATUM_STATE_DEV}" || fatal "z_stratum_root(): Failure mkfs on \"${STRATUM_STATE_DEV}\""
 }
 
 z_stratum_root() {
@@ -280,26 +389,44 @@ z_stratum_root() {
 	mkdir /run/stratum/images || fatal "z_stratum_root(): Failure create directory /run/stratum/images"
 	mkdir /run/stratum/state || fatal "z_stratum_root(): Failure create directory /run/stratum/state"
 
-	mount -t "${STRATUM_IMAGES_FS}" -o ro "${STRATUM_IMAGES_DEV}" /run/stratum/images || fatal "Failure mount \"${STRATUM_IMAGES_DEV}\" to /run/stratum/images"
-	info "/run/stratum/images mounted from ${STRATUM_IMAGES_DEV}"
+	mount -t "${STRATUM_IMAGES_FS}" -o rw "${STRATUM_IMAGES_DEV}" /run/stratum/images || fatal "z_stratum_root(): Failure mount \"${STRATUM_IMAGES_DEV}\" to /run/stratum/images"
+	info "z_stratum_root(): /run/stratum/images mounted from ${STRATUM_IMAGES_DEV}"
 
-	mount -t "${STRATUM_STATE_FS}" -o rw "${STRATUM_STATE_DEV}" /run/stratum/state || fatal "Failure mount \"${STRATUM_STATE_DEV}\" to /run/stratum/state"
-	info "/run/stratum/state mounted from ${STRATUM_STATE_DEV}"
+	mount -t "${STRATUM_STATE_FS}" -o rw "${STRATUM_STATE_DEV}" /run/stratum/state || fatal "z_stratum_root(): Failure mount \"${STRATUM_STATE_DEV}\" to /run/stratum/state"
+	info "z_stratum_root(): /run/stratum/state mounted from ${STRATUM_STATE_DEV}"
 
-	local STATE_DIR="/run/stratum/state/${STRATUM_ROOT_IMAGE}"
+	local LAYER_NUMBER=0
+	local IMAGE_HASH=
+	IMAGE_HASH=$(__stratum__resolve_image_hash "${STRATUM_ROOT_IMAGE}")
+	local ROOT_IMAGE_HASH_RESOLUTION_CODE=$?
+	if [ ${ROOT_IMAGE_HASH_RESOLUTION_CODE} -ne 0 ]; then
+		fatal "z_stratum_root(): Cannot read remote MANIFEST data. Exit with code: ${ROOT_IMAGE_HASH_RESOLUTION_CODE}."
+	fi
+	info "z_stratum_root(): Root image hash: ${IMAGE_HASH}"
+
+	local LOWERDIRS=
+
+	local STATE_DIR="/run/stratum/state/${IMAGE_HASH}"
 
 	if [ ! -d "${STATE_DIR}" ]; then
 		mkdir "${STATE_DIR}" || fatal "z_stratum_root(): Failure create state dir ${STATE_DIR}"
-		info "${STATE_DIR} state directory was created"
+		info "z_stratum_root(): ${STATE_DIR} state directory was created"
 	fi
-
-	local LAYER_NUMBER=0
-	local IMAGE_HASH="${STRATUM_ROOT_IMAGE}"
-	local LOWERDIRS=
 
 	while [ -n "${IMAGE_HASH}" ]; do
 		local IMAGE_DIR="/run/stratum/images/${IMAGE_HASH}"
-		[ -d "${IMAGE_DIR}" ] || fatal "z_stratum_root(): Image ${IMAGE_HASH} does not exist"
+		if [ -d "${IMAGE_DIR}" ]; then
+			if [ ! -f "${IMAGE_MANIFEST_FILE}" -o ! -f "${IMAGE_DATA_FILE}" ]; then
+				rm -rf "${IMAGE_DIR}" || fatal "Failure remove broken image dir \"${IMAGE_DIR}\""
+			fi
+		fi
+
+		if [ ! -d "${IMAGE_DIR}" ]; then
+			info "Downloading image ${IMAGE_HASH} ..."
+			__stratum__download_image "${IMAGE_HASH}"
+		else
+			info "${IMAGE_HASH} already exist"
+		fi
 
 		local IMAGE_MANIFEST_FILE="${IMAGE_DIR}/MANIFEST"
 		local IMAGE_DATA_FILE="${IMAGE_DIR}/DATA"
@@ -309,11 +436,11 @@ z_stratum_root() {
 
 		if [ ! -d "${LAYER_DIR}" ]; then
 			mkdir "${LAYER_DIR}" || fatal "z_stratum_root(): Failure create layer dir ${STATE_DIR}"
-			info "${LAYER_DIR} layer directory was created"
+			info "z_stratum_root(): ${LAYER_DIR} layer directory was created"
 		fi
 
 		mount -t squashfs -o ro,loop "${IMAGE_DATA_FILE}" "${LAYER_DIR}" || fatal "z_stratum_root(): Failure mount layer \"${IMAGE_DATA_FILE}\" to \"${LAYER_DIR}\""
-		info "${IMAGE_DATA_FILE} layer image was mounted to ${LAYER_DIR}"
+		info "z_stratum_root(): ${IMAGE_DATA_FILE} layer image was mounted to ${LAYER_DIR}"
 
 		if [ -n "${LOWERDIRS}" ]; then
 			LOWERDIRS="${LOWERDIRS}:${LAYER_DIR}"
@@ -321,27 +448,27 @@ z_stratum_root() {
 			LOWERDIRS="${LAYER_DIR}"
 		fi
 
-		local BASE_IMAGE_HASH=$(cat "${IMAGE_MANIFEST_FILE}" | grep -e "^BASE: " | rev | cut -d' ' -f1 | rev)
-
-		IMAGE_HASH="${BASE_IMAGE_HASH}"
+		IMAGE_HASH=$(cat "${IMAGE_MANIFEST_FILE}" | grep -e "^BASE: " | rev | cut -d' ' -f1 | rev)
 		let "LAYER_NUMBER=$LAYER_NUMBER+1"
 	done
+
+	mount -o remount,ro "${STRATUM_IMAGES_DEV}" || fatal "z_stratum_root(): Failure re-mount \"${STRATUM_IMAGES_DEV}\" as Read-Only."
 
 	local WORK_DIR="${STATE_DIR}/.work"
 
 	if [ ! -d "${WORK_DIR}" ]; then
 		mkdir "${WORK_DIR}" || fatal "z_stratum_root(): Failure create layer dir ${WORK_DIR}"
-		info "${WORK_DIR} work directory was created"
+		info "z_stratum_root(): ${WORK_DIR} work directory was created"
 	fi
 
 	local TOP_DIR="${STATE_DIR}/top"
 
 	if [ ! -d "${TOP_DIR}" ]; then
 		mkdir "${TOP_DIR}" || fatal "z_stratum_root(): Failure create layer dir ${TOP_DIR}"
-		info "${TOP_DIR} top directory was created"
+		info "z_stratum_root(): ${TOP_DIR} top directory was created"
 	fi
 
-	mount -t overlay -o "ro,lowerdir=${LOWERDIRS},workdir=${WORK_DIR},upperdir=${TOP_DIR}" none /newroot || fatal "z_stratum_root(): Failure mount overlay /newroot based on ${LOWERDIRS}"
+	mount -t overlay -o "ro,lowerdir=${LOWERDIRS},workdir=${WORK_DIR},upperdir=${TOP_DIR}" stratum_root /newroot || fatal "z_stratum_root(): Failure mount overlay /newroot based on ${LOWERDIRS}"
 }
 
 z_uncrypt() {
