Remove russian "c" from z_dhcp

diff --git a/initramfs/init b/initramfs/init
--- a/initramfs/init
+++ b/initramfs/init
@@ -36,16 +36,16 @@ fatal() {
 	exec /bin/busybox sh
 }
 
-z_dhсp() {
-	[ -n "$1" ] || fatal "z_dhсp(): Wrong argument error. Example: z_dhсp=\"eth0;eth1\""
+z_dhcp() {
+	[ -n "$1" ] || fatal "z_dhcp(): Wrong argument error. Example: z_dhcp=\"eth0;eth1\""
 
 	local FRIENDLY_ARGS=
 
 	FRIENDLY_ARGS=$(echo "$1" | sed -r 's/;/ /g')
 
 	for DEV in ${FRIENDLY_ARGS}; do
-		/sbin/ip link set up "${DEV}" || fatal "z_dhсp(): Failure set UP state for device ${DEV}."
-		/sbin/udhcpc -i "${DEV}" -n || fatal "z_dhсp(): Failure obtain lease for device ${DEV}."
+		/sbin/ip link set up "${DEV}" || fatal "z_dhcp(): Failure set UP state for device ${DEV}."
+		/sbin/udhcpc -i "${DEV}" -n || fatal "z_dhcp(): Failure obtain lease for device ${DEV}."
 	done
 }
 
