Add z_mkfs_ext4 function. Add z_stratum_reset_system function.

diff --git a/initramfs/init b/initramfs/init
--- a/initramfs/init
+++ b/initramfs/init
@@ -270,6 +270,20 @@ z_ssh() {
 	echo "pkill -f /usr/sbin/dropbear" >> /tmp/cleanup.sh
 }
 
+z_mkfs_ext4() {
+	[ -n "$1" ] || fatal "z_mkfs_ext4(dev,number-of-inodes,label): Wrong argument error. Example: z_mkfs_ext4=\"vg0/system,4194304,system\""
+
+	local DEV=
+	local NUMBER_OF_INODES=
+	local LABEL=
+
+	DEV=/dev/$(echo "$1" | cut -d, -f1)
+	NUMBER_OF_INODES=$(echo "$1" | cut -d, -f2)
+	LABEL=$(echo "$1" | cut -d, -f2)
+
+	mkfs.ext4 -L "${LABEL}"  -F -N "${NUMBER_OF_INODES}" "${DEV}"  || fatal "z_mkfs_ext4(): Failure mkfs.ext4 on \"${DEV}\""
+}
+
 __stratum__resolve_image_hash() {
 	local TARGET_IMAGE_ID="$1"
 
@@ -376,8 +390,8 @@ z_stratum_wipe() {
 	STRATUM_STATE_DEV=/dev/$(echo "$1" | cut -d, -f3)
 	STRATUM_STATE_FS=$(echo "$1" | cut -d, -f4)
 
-	mkfs.${STRATUM_IMAGES_FS} -L stratum-images -F -N 256    "${STRATUM_IMAGES_DEV}" || fatal "z_stratum_wipe(): Failure mkfs on \"${STRATUM_IMAGES_DEV}\""
-	mkfs.${STRATUM_STATE_FS}  -L stratum-state  -F -N 1048576 "${STRATUM_STATE_DEV}"  || fatal "z_stratum_wipe(): Failure mkfs on \"${STRATUM_STATE_DEV}\""
+	mkfs.${STRATUM_IMAGES_FS} -L stratum-images -F -N 256     "${STRATUM_IMAGES_DEV}" || fatal "z_stratum_wipe(): Failure mkfs on \"${STRATUM_IMAGES_DEV}\""
+	mkfs.${STRATUM_STATE_FS}  -L stratum-state  -F -N 4194304 "${STRATUM_STATE_DEV}"  || fatal "z_stratum_wipe(): Failure mkfs on \"${STRATUM_STATE_DEV}\""
 }
 
 z_stratum_wipe_state() {
@@ -389,7 +403,7 @@ z_stratum_wipe_state() {
 	STRATUM_STATE_DEV=/dev/$(echo "$1" | cut -d, -f1)
 	STRATUM_STATE_FS=$(echo "$1" | cut -d, -f2)
 
-	mkfs.${STRATUM_STATE_FS}  -L stratum-state  -F -N 1048576 "${STRATUM_STATE_DEV}"  || fatal "z_stratum_wipe_state(): Failure mkfs on \"${STRATUM_STATE_DEV}\""
+	mkfs.${STRATUM_STATE_FS}  -L stratum-state  -F -N 4194304 "${STRATUM_STATE_DEV}"  || fatal "z_stratum_wipe_state(): Failure mkfs on \"${STRATUM_STATE_DEV}\""
 }
 
 z_stratum_wipe_images() {
@@ -402,6 +416,114 @@ z_stratum_wipe_images() {
 	STRATUM_IMAGES_FS=$(echo "$1" | cut -d, -f2)
 
 	mkfs.${STRATUM_IMAGES_FS} -L stratum-images -F -N 256    "${STRATUM_IMAGES_DEV}" || fatal "z_stratum_wipe_images(): Failure mkfs on \"${STRATUM_IMAGES_DEV}\""
+}
+
+z_stratum_reset_system() {
+	[ -n "$1" ] || fatal "z_stratum_reset_system(system-dev,images-dev,image-name-or-hash): Wrong argument error. Example: z_stratum_root=\"vg0/system,vg0/stratum-images\""
+
+	local SYSTEM_DEV=
+	local STRATUM_IMAGES_DEV=
+
+	SYSTEM_DEV=/dev/$(echo "$1" | cut -d, -f1)
+	STRATUM_IMAGES_DEV=/dev/$(echo "$1" | cut -d, -f2)
+
+	mkdir /run/stratum || fatal "z_stratum_reset_system(): Failure create directory /run/stratum"
+	mkdir /run/stratum/images || fatal "z_stratum_reset_system(): Failure create directory /run/stratum/images"
+	mkdir /run/stratum/state || fatal "z_stratum_reset_system(): Failure create directory /run/stratum/state"
+
+	mount -t ext4 -o ro "${STRATUM_IMAGES_DEV}" /run/stratum/images || fatal "z_stratum_reset_system(): Failure mount \"${STRATUM_IMAGES_DEV}\" to /run/stratum/images"
+	info "z_stratum_reset_system(): /run/stratum/images mounted from ${STRATUM_IMAGES_DEV}"
+
+	local LAYER_NUMBER=0
+	local IMAGE_HASH=
+	IMAGE_HASH=$(__stratum__resolve_image_hash "system")
+	local ROOT_IMAGE_HASH_RESOLUTION_CODE=$?
+	if [ ${ROOT_IMAGE_HASH_RESOLUTION_CODE} -ne 0 ]; then
+		fatal "z_stratum_reset_system(): Cannot read remote MANIFEST data. Exit with code: ${ROOT_IMAGE_HASH_RESOLUTION_CODE}."
+	fi
+	info "z_stratum_reset_system(): Root image hash: ${IMAGE_HASH}"
+
+	local LOWERDIRS=
+
+	local STATE_DIR="/run/stratum/state/${IMAGE_HASH}"
+
+	if [ ! -d "${STATE_DIR}" ]; then
+		mkdir "${STATE_DIR}" || fatal "z_stratum_reset_system(): Failure create state dir ${STATE_DIR}"
+		info "z_stratum_reset_system(): ${STATE_DIR} state directory was created"
+	fi
+
+	while [ -n "${IMAGE_HASH}" ]; do
+		local IMAGE_DIR="/run/stratum/images/${IMAGE_HASH}"
+		local IMAGE_MANIFEST_FILE="${IMAGE_DIR}/MANIFEST"
+		local IMAGE_DATA_FILE="${IMAGE_DIR}/DATA"
+
+		if [ -d "${IMAGE_DIR}" ]; then
+			if [ ! -f "${IMAGE_MANIFEST_FILE}" -o ! -f "${IMAGE_DATA_FILE}" ]; then
+				warn "z_stratum_root(): Removing broken image dir \"${IMAGE_DIR}\" ..."
+				rm -rf "${IMAGE_DIR}" || fatal "z_stratum_root(): Failure remove broken image dir \"${IMAGE_DIR}\""
+			fi
+		fi
+
+		if [ ! -d "${IMAGE_DIR}" ]; then
+			info "z_stratum_root(): Downloading image ${IMAGE_HASH} ..."
+			__stratum__download_image "${IMAGE_HASH}"
+			if [ ${LAYER_NUMBER} -eq 0 -a "${IMAGE_HASH}" != "${STRATUM_ROOT_IMAGE}" ]; then
+				ln -s "${IMAGE_HASH}" "/run/stratum/images/${STRATUM_ROOT_IMAGE}" || fatal "z_stratum_root(): Cannot link \"/run/stratum/images/${STRATUM_ROOT_IMAGE}\" to \"${IMAGE_HASH}\""
+				ln -s "${IMAGE_HASH}" "/run/stratum/images/system" || fatal "z_stratum_pull(): Cannot link \"/run/stratum/images/system\" to \"${IMAGE_HASH}\""
+			fi
+		else
+			info "z_stratum_root(): ${IMAGE_HASH} already exist"
+		fi
+
+		local LAYER_NAME="layer${LAYER_NUMBER}"
+		local LAYER_DIR="${STATE_DIR}/${LAYER_NAME}"
+
+		if [ ! -d "${LAYER_DIR}" ]; then
+			mkdir "${LAYER_DIR}" || fatal "z_stratum_reset_system(): Failure create layer dir ${STATE_DIR}"
+			info "z_stratum_reset_system(): ${LAYER_DIR} layer directory was created"
+		fi
+
+		mount -t squashfs -o ro,loop "${IMAGE_DATA_FILE}" "${LAYER_DIR}" || fatal "z_stratum_reset_system(): Failure mount layer \"${IMAGE_DATA_FILE}\" to \"${LAYER_DIR}\""
+		info "z_stratum_reset_system(): ${IMAGE_DATA_FILE} layer image was mounted to ${LAYER_DIR}"
+
+		if [ -n "${LOWERDIRS}" ]; then
+			LOWERDIRS="${LOWERDIRS}:${LAYER_DIR}"
+		else
+			LOWERDIRS="${LAYER_DIR}"
+		fi
+
+		IMAGE_HASH=$(cat "${IMAGE_MANIFEST_FILE}" | grep -e "^BASE: " | rev | cut -d' ' -f1 | rev)
+		let "LAYER_NUMBER=$LAYER_NUMBER+1"
+	done
+
+	mount -o remount,ro "${STRATUM_IMAGES_DEV}" || fatal "z_stratum_reset_system(): Failure re-mount \"${STRATUM_IMAGES_DEV}\" as Read-Only."
+
+	local WORK_DIR="${STATE_DIR}/.work"
+
+	if [ ! -d "${WORK_DIR}" ]; then
+		mkdir "${WORK_DIR}" || fatal "z_stratum_reset_system(): Failure create layer dir ${WORK_DIR}"
+		info "z_stratum_reset_system(): ${WORK_DIR} work directory was created"
+	fi
+
+	local TOP_DIR="${STATE_DIR}/top"
+
+	if [ ! -d "${TOP_DIR}" ]; then
+		mkdir "${TOP_DIR}" || fatal "z_stratum_reset_system(): Failure create layer dir ${TOP_DIR}"
+		info "z_stratum_reset_system(): ${TOP_DIR} top directory was created"
+	fi
+
+	mkdir /run/stratum-root || fatal "z_stratum_reset_system(): Failure create stratum root dir /run/stratum-root"
+	mount -t overlay -o "ro,lowerdir=${LOWERDIRS},workdir=${WORK_DIR},upperdir=${TOP_DIR}" stratum_root /run/stratum-root || fatal "z_stratum_reset_system(): Failure mount overlay /run/stratum-root based on ${LOWERDIRS}"
+
+	mkfs.ext4 -L system -F -N 4194304 "${SYSTEM_DEV}" || fatal "z_stratum_reset_system(): Failure mkfs.ext4 on \"${SYSTEM_DEV}\""
+
+	mkdir /run/system-root || fatal "z_stratum_reset_system(): Failure create stratum root dir /run/system-root"
+	mount -t ext4 "${SYSTEM_DEV}" /run/system-root || fatal "z_stratum_reset_system(): Failure mount system root ${SYSTEM_DEV} to /run/system-root"
+
+	echo "Coping system files... Please wait a little bit..."
+	cp -a /run/stratum-root/. /run/system-root/ || fatal "z_stratum_reset_system(): Failure to copy system files."
+
+	umount /run/system-root || fatal "z_stratum_reset_system(): Failure unmount system root /run/system-root"
 }
 
 z_stratum_pull() {
@@ -685,7 +807,7 @@ if [ -d /newroot/lib ]; then
 				info "Skip modules syncing. Looks like modules are same in initramfs and rootfs"
 			fi
 	else
-		info "Skip modules syncing due the initramfs has not embedded kernel modules."
+		info "Skip modules syncing due the initramfs has not embedded such kernel modules."
 	fi
 
 else
